# Generated by Django 5.2.7 on 2025-11-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('Matina', 'Matina'), ('Toril', 'Toril')], default='Matina', max_length=50),
        ),
    ]
