# Generated by Django 5.2.7 on 2025-11-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
