# Generated by Django 5.2.7 on 2025-11-01 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='PurchaseFeedback',
        ),
        migrations.AlterModelOptions(
            name='productfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Feedback', 'verbose_name_plural': 'Product Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='purchasefeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Purchase Feedback', 'verbose_name_plural': 'Purchase Feedbacks'},
        ),
    ]
