# Generated by Django 5.2.7 on 2025-11-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
    ]
