# Generated by Django 5.2.7 on 2025-11-01 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_picture', models.ImageField(blank=True, null=True, upload_to='pet_pics/')),
                ('pet_name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age_value', models.IntegerField()),
                ('age_unit', models.CharField(choices=[('months', 'Months'), ('years', 'Years')], max_length=10)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('weight_lbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
