# Generated by Django 5.2.7 on 2025-11-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='branch',
            field=models.CharField(choices=[('Matina', 'Matina'), ('Toril', 'Toril')], default='Matina', max_length=50),
        ),
    ]
