# Generated by Django 5.2.7 on 2025-11-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('services', '0007_service_addon_price_service_standalone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='add_ons',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_solo': True}, related_name='appointment_addons', to='services.service'),
        ),
    ]
