# Generated by Django 5.2.7 on 2025-11-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hours',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
