# Generated by Django 5.2.7 on 2025-11-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_hours_service_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='may_overlap',
            field=models.BooleanField(default=False),
        ),
    ]
