# Generated by Django 5.2.7 on 2025-10-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.CharField(choices=[('Matina', 'Matina'), ('Toril', 'Toril')], default='Matina', max_length=32),
        ),
    ]
