# Generated by Django 5.2.7 on 2025-10-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pet Food & Treats', 'Pet Food & Treats'), ('Grooming & Hygiene', 'Grooming & Hygiene'), ('Health & Wellness', 'Health & Wellness'), ('Accessories & Toys', 'Accessories & Toys'), ('Cages & Bedding', 'Cages & Bedding'), ('Feeding Supplies', 'Feeding Supplies'), ('Cleaning Supplies', 'Cleaning Supplies')], max_length=128),
        ),
    ]
