# Generated by Django 5.2.7 on 2025-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='transaction_type',
            field=models.CharField(choices=[('addition', 'Product Added'), ('restock', 'Restock'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('damaged', 'Damaged/Loss'), ('return', 'Customer Return')], max_length=20),
        ),
    ]
