# Generated by Django 5.2.7 on 2025-11-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_producthistory_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
