# Generated by Django 5.2.7 on 2025-11-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
